name: Build

on:
  pull_request:

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build --stacktrace

  unit-tests:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Execute unit tests
        run: ./gradlew allTests --stacktrace

#      - name: Generate test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit_tests_report.html
#          path: androidApp/build/reports/tests/testDebugUnitTest/